email:
  mail:
    smtp:
      starttls: true
      auth: true
      host: smtp.gmail.com
      port: 587
    credential:
      username: username@gmail.com
      password: password
    attachmentFilePath: logs/email-app.log
    subject: "Notification: Credential Update"
    body: This is a test email with attachment.
    attachmentPassword: SimplePassword

  emailCron: "0 30 19 * * ?"

logging:
  file: logs/email-app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"